/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_agora_rtc_RtcEngine */

#ifndef _Included_io_agora_rtc_RtcEngine
#define _Included_io_agora_rtc_RtcEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_agora_rtc_RtcEngine
 * Method:    nativeCreate
 * Signature: (Lio/agora/rtc/IRtcEngineEventHandler;)J
 */
JNIEXPORT jlong JNICALL Java_io_agora_rtc_RtcEngine_nativeCreate
  (JNIEnv *, jclass cls, jobject handler);

/*
 * Class:     io_agora_rtc_RtcEngine
 * Method:    nativeJoinChannel
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ISSZI)V
 */
JNIEXPORT void JNICALL Java_io_agora_rtc_RtcEngine_nativeJoinChannel
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jint, jshort, jshort, jboolean, jint);

/*
 * Class:     io_agora_rtc_RtcEngine
 * Method:    nativeLeave
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_agora_rtc_RtcEngine_nativeLeave
  (JNIEnv *, jclass cls, jlong instance);

/*
 * Class:     io_agora_rtc_RtcEngine
 * Method:    nativePoll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_agora_rtc_RtcEngine_nativePoll
  (JNIEnv *, jclass cls, jlong instance);

/*
 * Class:     io_agora_rtc_RtcEngine
 * Method:    nativeDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_agora_rtc_RtcEngine_nativeDestroy
  (JNIEnv *, jclass cls, jlong instance);

#ifdef __cplusplus
}
#endif
#endif
